[development]
address = "localhost"
port = 8000
reactrix = "tcp://localhost4:5660/"

[development.databases]
events = { url = "postgres://events:events@localhost4/events" }

[production]
address = "0.0.0.0"
port = 8000
reactrix = "tcp://reactrix:5660/"

[production.databases]
events = { url = "postgres://events:events@db/events" }
